### ISSUE TITLE
Transforms make valid invalid inputs

### ISSUE THREAD

**Issue by mapolonio** [oliverbrooks/hannibal#10]
Example:

```
var simpleValidator = hannibal.create({
  type: 'object',
  schema: {
    shouldBeNumber: {
      type: 'number',
      transforms: 'toFloat'
    }
  }
});
simpleValidator({
  shouldBeNumber: 'notAnumber'
}).isValid; //returns true
```

Date fails too:

```
var simpleValidator2 = hannibal.create({
  type: 'object',
  schema: {
    shouldBeDate: {
      type: 'date',
      transforms: 'toDate'
    }
  }
});
simpleValidator2({
  shouldBeDate: 'notAdate'
}).isValid; //true again
```

**Comment by orangemug** [comment]
@mapolonio I've made a fix for this in PR #11, do you want to give it a test see if it makes sense to you?

**Comment by pasupulaphani** [comment]
Fix is available with the latest release. https://github.com/pearlshare/hannibal/releases/tag/0.3.5

**Comment by orangemug** [comment]
@pasupulaphani don't forget to update npm (https://www.npmjs.com/package/hannibal)

**Comment by pasupulaphani** [comment]
Unfortunately I do not have permissions to update. @oliverbrooks is away. Sorry about that.

**Comment by orangemug** [comment]
@pasupulaphani no worries @oliverbrooks can release on his return, @mapolonio to install the latest you can just run

```
npm install pearlshare/hannibal
```

Which will grab it from github instead of npm

**Comment by mapolonio** [comment]
Thanks, I'll give it a try.

**Comment by orangemug** [comment]
@mapolonio just to let you know @oliverbrooks published _v0.3.5_ to npm ~3 weeks back, the following should work again.

```
npm install hannibal
```

**Comment by mapolonio** [comment]
Thanks for the reminder, I'll change the dependency ;)
